"""empty message

Revision ID: 2883137d8102
Revises: 2197b9a8e4c8
Create Date: 2024-03-20 13:26:30.073347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2883137d8102"
down_revision: Union[str, None] = "2197b9a8e4c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("follow_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["follow_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "follow_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
