"""empty message

Revision ID: 8754f86493ee
Revises: 2883137d8102
Create Date: 2024-03-21 11:49:58.069238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8754f86493ee"
down_revision: Union[str, None] = "2883137d8102"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("followers", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("following", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "following")
    op.drop_column("users", "followers")
    # ### end Alembic commands ###
